In [35]:
import os
import sys
import math as m
import pandas as pd
import csv
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

plt.style.use('ggplot')


In [36]:
## Import data for Shanghai
weibo_SH_pt = pd.read_csv("/Users/wenfeixu/Dropbox (MIT)/MIT/CDDL/STL_WeChatProject/0_data/Weibo/Shanghai/shanghai_poi_20151211.csv",encoding="utf-8")
weibo_SH = pd.read_csv("/Users/wenfeixu/Dropbox (MIT)/MIT/CDDL/STL_WeChatProject/1_ShapeFiles/Weibo/Weibo_SH_landscanaggregated_gcj02.csv",encoding="utf-8")
landscan_SH = pd.read_csv("/Users/wenfeixu/Dropbox (MIT)/MIT/CDDL/STL_WeChatProject/1_ShapeFiles/China_LandScan2014/GCJ02/shanghai_landscan_2014_corrected_gcj02.csv",encoding="utf-8")
# LS = pd.read_csv(")


In [37]:
## Make sure everything imported correctly for Weibo Data
print weibo_SH.columns
weibo_SH.head()

Index([u'FID_1', u'pointid', u'grid_code', u'population', u'distance_m', u'Count_', u'Sum_catego', u'Sum_checki', u'Sum_chec_1', u'Sum_city', u'Sum_dianpi', u'Sum_distan', u'Sum_distri', u'Sum_enterp', u'Sum_hereno', u'Sum_lat', u'Sum_lon', u'Sum_photo_', u'Sum_pintu', u'Sum_postco', u'Sum_provin', u'Sum_sale', u'Sum_select', u'Sum_spent', u'Sum_tip_nu', u'Sum_todo_n', u'Sum_weibo_', u'Sum_rowid_'], dtype='object')


FID_1   pointid  grid_code  population    distance_m  Count_  Sum_catego  \
0      0  10501165        691         691  76354.332567       0           0   
1      1  10501164       2679        2679  76939.869577       0           0   
2      2  10501166        274         274  75772.629127       0           0   
3      3  10501163        278         278  77529.153296       0           0   
4      4  10501167       4051        4051  75194.848230       0           0   

   Sum_checki  Sum_chec_1  Sum_city    ...     Sum_pintu  Sum_postco  \
0           0           0         0    ...             0           0   
1           0           0         0    ...             0           0   
2           0           0         0    ...             0           0   
3           0           0         0    ...             0           0   
4           0           0         0    ...             0           0   

   Sum_provin  Sum_sale  Sum_select  Sum_spent  Sum_tip_nu  Sum_todo_n  \
0           0         0           0          0           0           0   
1           0         0           0          0           0           0   
2           0         0           0          0           0           0   
3           0         0           0          0           0           0   
4           0         0           0          0           0           0   

   Sum_weibo_  Sum_rowid_  
0           0           0  
1           0           0  
2           0           0  
3           0           0  
4           0           0  

[5 rows x 28 columns]

In [38]:
## Make sure everything imported correctly for LandScan data
print landscan_SH.columns
landscan_SH.head()

Index([u'pointid', u'grid_code', u'population', u'distance_m'], dtype='object')


pointid  grid_code  population    distance_m
0  10501165        691         691  76354.332567
1  10501164       2679        2679  76939.869577
2  10501166        274         274  75772.629127
3  10501163        278         278  77529.153296
4  10501167       4051        4051  75194.848230

In [39]:
## Drop unnecessary columns in dataframe and give columns more accurate names for WEIBO

weibo_SH = weibo_SH.drop([ u'population', u'distance_m', u'Sum_catego',\
                          u'Sum_chec_1', u'Sum_city', u'Sum_dianpi', u'Sum_distan', u'Sum_distri',\
                          u'Sum_enterp', u'Sum_hereno', u'Sum_lat', u'Sum_lon', u'Sum_photo_', u'Sum_pintu', u'Sum_postco',\
                          u'Sum_provin', u'Sum_sale', u'Sum_select', u'Sum_spent', u'Sum_tip_nu', u'Sum_todo_n', u'Sum_weibo_',\
                          u'Sum_rowid_'],axis = 1)


weibo_SH.columns = ['FID','ID','grid_code','count_POIs','sum_checkin']
weibo_SH.head()



FID        ID  grid_code  count_POIs  sum_checkin
0    0  10501165        691           0            0
1    1  10501164       2679           0            0
2    2  10501166        274           0            0
3    3  10501163        278           0            0
4    4  10501167       4051           0            0

In [47]:
## Drop unnecessary columns in dataframe and give columns more accurate names for LANDSCAN

landscan_SH = landscan_SH.drop(['distance_m'],axis = 1)
landscan_SH.columns = ['ID','grid_code','pop_count']
landscan_SH.head()



ID  grid_code  pop_count
0  10501165        691        691
1  10501164       2679       2679
2  10501166        274        274
3  10501163        278        278
4  10501167       4051       4051

In [1]:
## Histogram of Logged Landscan count

fig = plt.figure()
ax = fig.add_subplot(111)
ax.hist([m.log(x+1) for x in landscan_SH.pop_count],bins=30)


ax.set_xlabel('Grid IDs from Landcsan')
ax.set_ylabel('Normalized count on grid')
ax.set_title('Logged Landscan counts per grid')
plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [45]:
## Histogram of Logged Weibo count

fig = plt.figure()
ax = fig.add_subplot(111)
ax.hist([m.log(x+1) for x in weibo_SH.sum_checkin],bins=30)
# ax.hist(weibo_SH.sum_checkin,bins=20)



ax.set_xlabel('Grid IDs from Landcsan')
ax.set_ylabel('Normalized count on grid')
ax.set_title('Logged Weibo counts per grid')
plt.tight_layout()
plt.show()

In [53]:
##  Show scatter plots of original weibo and landscan side by side


fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(landscan_SH.ID, [x/float(max(landscan_SH.pop_count)) for x in landscan_SH.pop_count],marker=',',c='r',s =18)
ax.scatter(weibo_SH.ID, [x/float(max(weibo_SH.sum_checkin)) for x in weibo_SH.sum_checkin],marker = 'o',c='b',s = 18)

ax.set_xlabel('ID')
ax.set_ylabel('Frequency')
ax.set_title('Raw Weibo and Landscan Counts by ID ')
plt.tight_layout()
plt.show()


# plt.scatter(weibo_SH.ID, weibo_SH.sum_checkin)
# plt.show()

In [54]:
##  Show scatter plots of z-scores of weibo and landscan
from scipy import stats


fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(landscan_SH.ID, stats.zscore(landscan_SH.pop_count),marker=',',c='r',s =18)
ax.scatter(weibo_SH.ID, stats.zscore(weibo_SH.sum_checkin),marker = 'o',c='b',s = 18)

ax.set_xlabel('ID')
ax.set_ylabel('Z-Score')
ax.set_title('Scatter Plot of Z-Scores for Weibo and Landscan')
plt.tight_layout()
plt.show()


# plt.scatter(weibo_SH.ID, weibo_SH.sum_checkin)
# plt.show()

In [25]:
# ## Test plot with colormapping

# landscan_SH_stddev = [(x - np.mean(landscan_SH.pop_count))/float(np.std(landscan_SH.pop_count)) for x in landscan_SH.pop_count]
# landscan_SH_stddev_NORM = [(x - min(landscan_SH_stddev))/float(max(landscan_SH_stddev)-min(landscan_SH_stddev)) for x in landscan_SH_stddev]

# cm = plt.get_cmap('hsv')
# plt.scatter(landscan_SH.ID, landscan_SH.pop_count,marker=',', c=landscan_SH_stddev_NORM, cmap=cm,s =8)

# plt.colorbar()
# plt.show()

KeyboardInterrupt: 

In [55]:
## Correlation analysis for raw data
corr_SH = np.corrcoef(landscan_SH.sort('ID', ascending =True).pop_count, weibo_SH.sort('ID', ascending =True).sum_checkin)
print corr_SH

[[ 1.          0.46056194]
 [ 0.46056194  1.        ]]


In [56]:
## Correlation analysis for LOGGED data
corr_SH = np.corrcoef([m.log(x+1) for x in landscan_SH.sort('ID', ascending =True).pop_count], [m.log(x+1) for x in weibo_SH.sort('ID', ascending =True).sum_checkin])
print corr_SH

[[ 1.          0.57095237]
 [ 0.57095237  1.        ]]


In [21]:
# ## Create joined dataset 
# joined_SH = pd.merge(landscan_SH.sort('ID', ascending =True), weibo_SH.sort('ID', ascending =True), how='inner')

# ## Find correlation of just non-zero grids
# corr_SH_new = np.corrcoef(joined_SH[joined_SH.sum_checkin !=0].pop_count, joined_SH[joined_SH.sum_checkin !=0].sum_checkin)
# print corr_SH_new

[[ 1.          0.45161952]
 [ 0.45161952  1.        ]]


In [61]:
## Find "subtraction" between Landscan and Weibo z-scores of LOGGED counts

fig = plt.figure()
ax = fig.add_subplot(111)

ax.scatter(landscan_SH.ID,  stats.zscore([m.log(x+1) for x in landscan_SH.pop_count])- stats.zscore([m.log(x+1) for x in weibo_SH.sum_checkin]),marker=',',c='r',s =18)

ax.set_xlabel('Grid IDs from Landcsan')
ax.set_ylabel('Diff of Normalized Counts')
ax.set_title('"Subtraction" between Weibo and Landscan Z-Scores counts by grid')
plt.tight_layout()
plt.show()



In [62]:
## Export Results of Z-score and subtraction analysis

results_SH = landscan_SH
results_SH['weibo_count'] = weibo_SH['sum_checkin']
results_SH['zscore_Landscan']=stats.zscore(landscan_SH.pop_count)
results_SH['zscore_ln_Landscan']=stats.zscore([m.log(x+1) for x in landscan_SH.pop_count])
results_SH['zscore_Weibo']=stats.zscore([m.log(x+1) for x in weibo_SH.sum_checkin])
results_SH['zscore_ln_Weibo']=stats.zscore(weibo_SH.sum_checkin)


results_SH['diff'] = results_SH['zscore_Landscan']-results_SH['zscore_Weibo']
results_SH['diff_ln'] = results_SH['zscore_ln_Landscan']-results_SH['zscore_ln_Weibo']
results_SH.head()

results_SH.to_csv('/Users/wenfeixu/Dropbox (MIT)/MIT/CDDL/STL_WeChatProject/0_data/Weibo_Landscan_Analysis/weibo_landscan_results_SH.csv',encoding="utf-8")

In [22]:
# ##  Show scatter plots of weibo and landscan side by side with only non-zero Weibo checkins

# # plt.scatter(weibo_SH.ID,[a/max(weibo_SH.sum_checkin) for a in weibo_SH.sum_checkin])

# fig = plt.figure()
# ax = fig.add_subplot(111)
# ax.scatter(joined_SH[joined_SH.sum_checkin !=0].ID, [(x - np.mean(joined_SH[joined_SH.sum_checkin !=0].pop_count))\
#                                                      /float(np.std(joined_SH[joined_SH.sum_checkin !=0].pop_count)) for x in \
#                                                      joined_SH[joined_SH.sum_checkin !=0].pop_count]\
# ,marker=',',c='r',s =14)
# ax.scatter(joined_SH[joined_SH.sum_checkin !=0].ID, [(x- np.mean(joined_SH[joined_SH.sum_checkin !=0].sum_checkin))\
#                                                       /float(np.std(joined_SH[joined_SH.sum_checkin !=0].sum_checkin)) for x in\
#                                                       joined_SH[joined_SH.sum_checkin !=0].sum_checkin]\
#                                                       ,marker = 'o',c='b',s = 14)

# ax.set_xlabel('Grid IDs from Landcsan')
# ax.set_ylabel('Normalized count on grid')
# ax.set_title('Weibo and Landscan counts per grid')
# plt.tight_layout()
# plt.show()

